name: coverage
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches:
            - main
jobs:
    coverage:
        name: Collecting coverage
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v3

            - name: Use Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.4.0

            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  test-script: pnpm test
